### PR TITLE
Changed JS to follow jQuery plugin conventions

### PR DESCRIPTION
**Pull request by eoinkelly**
I had a go at changing this to follow jQuery plugin conventions a little more - I mostly followed http://stefangabos.ro/jquery/jquery-plugin-boilerplate-oop/ - even if you choose not to accept this, it might help point you in the right direction. I have more work I want to do on this but thought it better to submit the pull request earlier rather than later.
cheers
/Eoin/

### CODE REVIEW

**Comment by simanek** [comment]
Will have to test to make sure it works the same. I must say, thank you for making this code better by following a standard, but it's unfortunate that now the code seems much more difficult to read by someone with a limited knowledge of JavaScript's idiosyncrasies. With my understanding of JavaScript I don't think I could reverse-engineer this new code.

**Comment by eoinkelly** [comment]
That will probably make it hard for you to maintain this in future so maybe it's best if you revert my pull request. I'm using this as a learning experience too - I'll update my fork with a more commented version as I work my way through it and I'll submit a pull request then which might be more helpful to you.

**Comment by simanek** [comment]
Thanks! Now I'm off to figure out how to revert a pull request....

**Comment by simanek** [comment]
Eh, I'm going to keep your changes. I looked it over carefully just now. I think I get it. I wish JavaScript didn't have so many different ways to do the same things. I picked up HTML + CSS with very little effort. Just when I think I'm getting a handle on JS some smarter person comes along points out a different method. Oh well. Thanks again!

**Comment by simanek** [comment]
Going to have to revert after all: just tested this (I know, a little late) and it doesn't work. ?

**Comment by eoinkelly** [comment]
Sorry about that - I pushed too soon :-(. I got lost in the weeds researching best practices and didn't test properly. Doh. I'll sort my fork out when I get a chance and submit another pull request for your consideration when it's fully commented etc.

**Pull request merged**
