### PR TITLE
Allow rows to be created by window height if window height is larger than document height

### PR DESCRIPTION
**Pull request by tomeara**
I was having a problem displaying rows, because the document had not fully loaded by the time the hugrid had. So, I made this change that determines which is larger at the time the script is called: window height or document.body height.

### CODE REVIEW

**Comment by simanek** [comment]
To be clear, the above message is in reference to the example_bootstrap.html file (d2888bF).

028d914 versus e5389f4
Does e5389f4 nullify the changes committed in 028d914? It looks like that's the case, but I don't have a really strong understanding of GIT. I guess if the third does nullify the first, I wonder why the first hasn't simply been deleted.

Regardless, e5389f4 looks like a good change and after testing it seems to work. 

Let me take a look at example_bootstrap.html to see if I can figure out how to make the content match the change to the overlay grid.

**Comment by tomeara** [comment]
I suppose I could've squashed the commits. The e5389f4 commit just was a refactor to add both document.body and window. Before I just added window height for my own use. The later commit should be more inclusive. Let me know if you want help with the content there, but yeah, I'm sure that there could be content more pertinent to bootstrap there. 

From my phone. Please forgive any typos.

**Comment by simanek** [comment]
Oh hey! That wasn't a critique of your commit practices! :) I’m just learning this whole version control/git thing on my own and I wanted to make sure I understood the intent of the two commits.

Thanks for your help on this, by the way. I’m also just self-educating with JavaScript and I don't have a strong understanding of little details like the difference between document.height and window.height. Much appreciated!

**Comment by tomeara** [comment]
No worries! :) I'm glad I can help!

**Pull request merged**
