### PR TITLE
simple javascript specific code fixes

### PR DESCRIPTION
**Pull request by lucasrenan**
it's just simple js specific code fixes. I will do a complete refactor to solve the global variables problem :)

### CODE REVIEW

**Comment by lucasrenan** [comment]
@simanek,

any problem with the code?

**Comment by simanek** [comment]
Sorry for the long delay. I have two things working against me: Not fluent with GIT. I'm pretty busy.

I went ahead and accepted your commit. Now I just need to figure out how to pull the new code down so I can test it. :D

**Comment by lucasrenan** [comment]
ok jason, thanks for accepted it :)
so, you can pull the code running `git pull origin master` from command line to your local repo.
now I will work to solve the global variables problem.

**Comment by simanek** [comment]
Thanks for the help! (GIT _and_ Heads-Up Grid)

I'm running Ubuntu Linux and have just discovered RabbitVCS which integrates GIT and SVN with the OS's file manager. Works pretty slick if you know which command is the one you need. I've finally accepted that my infrequent use of GIT and SVN makes learning the command line stuff pretty difficult.

**Pull request merged**
